apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    workload: jenkins-fargate
spec:
  serviceAccountName: myjenkins
  securityContext:
    runAsUser: 0
    fsGroup: 0   
     
  
  containers:
  - name: maven-fargate
    image: maven:3.6.0-jdk-8-alpine
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "2048i"
        cpu: "1024m"
    command:
    - cat
    tty: true
  - name: helm-fargate
    image: alpine/helm:3.5.2
    command:
    - cat
    tty: true  
    
