apiVersion: v1
kind: Pod
metadata:
  labels:
    workload: jenkins-fargate
spec:
  serviceAccountName: myjenkins
  securityContext:
    runAsUser: 0
    fsGroup: 0
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket
   
  containers:
  - name: maven-fargate
    image: maven:3.6.0-jdk-8-alpine
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 1700m
        memory: 1536Mi
      requests:
        cpu: 1000m
        memory: 1024Mi
  
  - name: docker-builder-fargate
    image: 'docker:latest'
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /run/docker.sock
